### ISSUE TITLE
Make openai calls cost less with this one weird trick

### ISSUE THREAD

**Issue by architectdrone** [YOUSY0US3F/minecraft-gpt-god-plugin#35]
(idk if this will work, haven't tried this yet)

You are using "gpt-4o": https://github.com/YOUSY0US3F/minecraft-gpt-god-plugin/blob/6c04f78ec49f69b35863fc9c8a0fd31cca4f0d93/src/main/java/net/bigyous/gptgodmc/GPT/GPTModels.java#L11

gpt-4o-2024-08-06 is cheaper: https://openai.com/api/pricing/

caveat: I don't know why it is cheaper 🤷🏻‍♂️ maybe make the model directly configurable from the yaml?

this seems like an easy fix so I can do it if u want (in a bit)

**Comment by YOUSY0US3F** [comment]
just saw your PR, I'll test and merge it
