### ISSUE TITLE
Confused by nothing actually happening, and the plugin spits out errors to the log, No scoreboard, No functionality.

### ISSUE THREAD

**Issue by CandyPxUwU** [YOUSY0US3F/minecraft-gpt-god-plugin#44]
Tried with GPT-4-Turbo, 4o, and 4o-mini on java 22 with windows server 2016 and AMP, as well as MC 1.21.1

**Relevant log snippet:**

> ``[gptgodmc]: EpicAppraiser said: WAKEN. GET OFF!!!
> Console20:11:11
> "function": {
> "name": "teleport",
> "description": "teleport a player to another player or a structure",
> "parameters": {
> "type": "object",
> "properties": {
> "playerName": {
> "type": "string",
> "description": "name of the player to be teleported"
> },
> "destination": {
> "type": "string",
> "description": "The name of the player or Structure the player will be sent to"
> }
> }
> }
> }
> },
> {
> "type": "function",
> "function": {
> "name": "command",
> "description": "Describe a series of events you would like to take place, taking into consideration the limitations of minecraft",
> "parameters": {
> "type": "object",
> "properties": {
> "prompt": {
> "type": "string",
> "description": "a description of what will happen"
> }
> }
> }
> }
> }
> ],
> "tool_choice": "auto"
> }
> INFO20:11:11
> [gptgodmc]: Making POST request
> [gptgodmc]: Making POST request
> [gptgodmc]: Making POST request
> Console20:11:12
> }
> ],
> "refusal": null
> },
> "logprobs": null,
> "finish_reason": "tool_calls"
> }
> ],
> "usage": {
> "prompt_tokens": 468,
> "completion_tokens": 64,
> "total_tokens": 532,
> "completion_tokens_details": {
> "reasoning_tokens": 0
> }
> },
> "system_fingerprint": "[hidden]"
> }
> WARN20:11:12
> Exception in thread "pool-20-thread-3" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected an int but was BEGIN_OBJECT at line 40 column 35 path $.usage.
> at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397)
> at com.google.gson.Gson.fromJson(Gson.java:1227)
> at com.google.gson.Gson.fromJson(Gson.java:1137)
> at com.google.gson.Gson.fromJson(Gson.java:1047)
> at com.google.gson.Gson.fromJson(Gson.java:982)
> at gptgodmc-0.1.4-all.jar//net.bigyous.gptgodmc.GPT.GptActions.processResponse(GptActions.java:412)
> at gptgodmc-0.1.4-all.jar//net.bigyous.gptgodmc.GPT.GptAPI.lambda$send$1(GptAPI.java:154)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> at java.base/java.lang.Thread.run(Thread.java:1570)
> Caused by: java.lang.IllegalStateException: Expected an int but was BEGIN_OBJECT at line 40 column 35 path $.usage.
> at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1211)
> at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
> at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:241)
> at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
> at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186)
> at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144)
> at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
> at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
> at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
> ... 9 more``

**Comment by YOUSY0US3F** [comment]
Hmm, do you have the whole log file?

**Comment by CandyPxUwU** [comment]
Indeed I do! also, chatgpt said "your code is expecting an integer, but the JSON response contains an object at the location where an integer was expected."

[latest.log](https://github.com/user-attachments/files/17000735/latest.log)

**Comment by YOUSY0US3F** [comment]
```
[17:23:25] [pool-20-thread-3/INFO]: [gptgodmc] recieved response from OpenAI: {
  "id": "chatcmpl-A7ArMZvsiTD36CQLlOgHzZuoy7MqQ",
  "object": "chat.completion",
  "created": 1726273404,
  "model": "gpt-4o-2024-05-13",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": null,
        "tool_calls": [
          {
            "id": "call_Eu8YRu4frPEcGUT9oeVb0kvH",
            "type": "function",
            "function": {
              "name": "announce",
              "arguments": "{\"message\": \"Welcome to your new world! Enjoy the clear day.\"}"
            }
          },
          {
            "id": "call_w7tb13dv4DDeIiOcJ7H2GCAk",
            "type": "function",
            "function": {
              "name": "setObjective",
              "arguments": "{\"objective\": \"Explore and gather resources to survive.\"}"
            }
          }
        ],
        "refusal": null
      },
      "logprobs": null,
      "finish_reason": "tool_calls"
    }
  ],
  "usage": {
    "prompt_tokens": 407,
    "completion_tokens": 60,
    "total_tokens": 467,
    "completion_tokens_details": {
      "reasoning_tokens": 0
    }
  },
  "system_fingerprint": "fp_25624ae3a5"
}
```
It seems GPT did try to send a message and set an objective. But GSON broke trying to parse the output. I think I found the culprit, it looks like OpenAI slightly changed the format of the responses. I'll put out a fix

**Comment by YOUSY0US3F** [comment]
https://modrinth.com/plugin/minecraft-gpt-god-plugin/version/0.1.5 I put out a fix for this, thanks for catching this issue

**Comment by CandyPxUwU** [comment]
Thanks yousef!
