### ISSUE TITLE
can you make it where you can change the prompt in the config?

### ISSUE THREAD

**Issue by bananaDevMan** [YOUSY0US3F/minecraft-gpt-god-plugin#47]
i want to change it

i had a discord bot do this by reading a file on startup with the prompt

**Comment by bananaDevMan** [comment]
oops, sorry for making it an issue, i dont use github much

**Comment by YOUSY0US3F** [comment]
Don't worry, this is a valid way to use Github issues. I'm actually currently working on this feature.

**Comment by YOUSY0US3F** [comment]
https://modrinth.com/plugin/minecraft-gpt-god-plugin/version/0.1.6
This feature is now in the new version

**Comment by bananaDevMan** [comment]
awesome, a lot easier than compiling from source haha
