### ISSUE TITLE
error getting world (I don't have the island map)

### ISSUE THREAD

**Issue by joep26020** [YOUSY0US3F/minecraft-gpt-god-plugin#50]
.

**Comment by YOUSY0US3F** [comment]
You can download the worlds folder here https://legacy.curseforge.com/minecraft/worlds/bigyous-minegpt-worlds/files. You can use your own minecraft worlds in the worlds folder but you will have to specify it in the config file

**Comment by YOUSY0US3F** [comment]
If you are unsure how to install the worlds folder follow the tutorial here https://youtu.be/uyVlkg75UVk

**Comment by joep26020** [comment]
> You can download the worlds folder here https://legacy.curseforge.com/minecraft/worlds/bigyous-minegpt-worlds/files. You can use your own minecraft worlds in the worlds folder but you will have to specify it in the config file

thanks!
